[package]
name = "simple-server"
version = "0.1.0"
authors = ["Wiktor Mazur <wiktormazur1@gmail.com>"]

[dependencies]
iron = "0.5"
mount = "0.3"
staticfile = "*"
router = "*"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0"